<a href="https://colab.research.google.com/github/Aanchal0102/Data_analyst_ineternship/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array Dimensions

1D Array

2D Array

3D Array

In [5]:
import numpy as np     # importing numpy library

In [6]:
A = np.array(5)        # Scalar Array
A

import numpy as np      # importing numpy library

A = np.array(5)         # Scalar Array
print(A)
print("Shape of A:", A.shape)
print("Number of dimensions of A:", A.ndim)

5
Shape of A: ()
Number of dimensions of A: 0


In [7]:
np.ndim(A)               # Dimension method

import numpy as np      # importing numpy library

A = np.array(5)         # Scalar Array

dimension_of_A = np.ndim(A)   # Dimension method
print(dimension_of_A)

0


In [8]:
One = np.array([1, 2, 3, 4, 5])
Two = np.array([[1, 2, 3], [4, 5, 6]])
Three = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

import numpy as np      # importing numpy library

One = np.array([1, 2, 3, 4, 5])
Two = np.array([[1, 2, 3], [4, 5, 6]])
Three = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

print("Array 'One':")
print(One)
print("Dimensions of 'One':", One.ndim)

print("\nArray 'Two':")
print(Two)
print("Dimensions of 'Two':", Two.ndim)

print("\nArray 'Three':")
print(Three)
print("Dimensions of 'Three':", Three.ndim)

Array 'One':
[1 2 3 4 5]
Dimensions of 'One': 1

Array 'Two':
[[1 2 3]
 [4 5 6]]
Dimensions of 'Two': 2

Array 'Three':
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimensions of 'Three': 3


In [9]:
Three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
Three.shape
np.ndim(Three)

3

In [11]:
np.ndim(One)
np.ndim(Two)
np.ndim(Three)

3

# List vs Numpy Array

In [12]:
list1 = [1,4.0,'apple']                     # List - Different Datatypes
arr = np.array([1, 2, 3, 4, 5])             # Array - Similar Datatypes

In [13]:
arr

array([1, 2, 3, 4, 5])

In [14]:
arr = np.array([1, 2, 3.9, 'apple'])        # Type Conversion

In [15]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [17]:
import numpy as np      # importing numpy library

arr = np.array([1, 2, 3, 4, 5])         # Allows Mathematical Operations

result_numpy = arr / 5
print("NumPy array divided by 5:", result_numpy)

list1 = [1, 2, 3, 4, 5]

try:
    result_list = list1 / 5
    print("List divided by 5:", result_list)
except TypeError as e:
    print(f"\nError when trying to divide a Python list by 5: {e}")

NumPy array divided by 5: [0.2 0.4 0.6 0.8 1. ]

Error when trying to divide a Python list by 5: unsupported operand type(s) for /: 'list' and 'int'


# More Advantages of Numpy Array over list

*   Array consumes less memory
*   Array are faster than lists



# Reshaping arrays

Reshaping means changing the shape of an array.

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array
newarr = arr.reshape(3, 4)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array

import numpy as np      # importing numpy library

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array
newarr = arr.reshape(3, 4)
print("Original 1D Array:\n", arr)
print("\nReshaped 2D Array (3x4):\n", newarr)

arr_again = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # 1D Array

# 1D to 2D Array
newarr_again = arr_again.reshape(2, 6)
print("\nOriginal 1D Array (again):\n", arr_again)
print("\nReshaped 2D Array (2x6):\n", newarr_again)

Original 1D Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Original 1D Array (again):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D Array (2x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [19]:
print (newarr)

import numpy as np      # importing numpy library

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# 1D to 3D Array

newarr = arr.reshape(2, 3, 2)    # x,y,z: x = matrix, y = rows, z = cols


In [ ]:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# print(newarr)

# Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [21]:
arr = np.array([1, 2, 3, 4])              # Accessing 1D Array

print(arr[3])

4


In [22]:
print(arr[0] + arr[1])                 # Addition of 2 elements

3


In [23]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  # Accessing 2D Array
arr.shape

# print(arr[0, 3])                          # 1st row 4th element
# print(arr[1, 1])                          # 2nd row 5th element
print(arr[1,3])

9


In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # Accessing 3D Array

arr3.shape
# print(arr3)
# print(arr3[0, 0, 2])               # 1st matrix, 1st row, 3rd column
# print(arr3[1, 1, 1])               # 1st matrix, 2nd row, 1st column
print(arr3[0,1,0])